### ISSUE TITLE
Access toggles-prefs from an artifactory

### ISSUE THREAD

**Issue by dmitry-ryadnenko-izettle** [erikeelde/toggles#22]
Hi Erik. 

Do you have any plans to upload `toggles-prefs` and `toggles-coroutines` to an artifactory? Meanwhile, do you think it will be an ok approach if we just make the middle layer that talks to the Toggles app ourselves?

**Comment by erikeelde** [comment]
Hi! @dmitry-ryadnenko-izettle 

It would be super fun to upload to an artifactory! And it is something I've been planning but it hasn't been a priority as I wasn't sure if the artifacts would be used so I've been holding off on it. I'll look into setting it up.. :) Thanks for reaching out!

Regarding writing your own middle layer that is the whole purpose of the ":toggles:core" module - to facilitate such use cases. The toggles app is written to cater to any and all libraries that want to talk to it. 

Do you think you have need for the "prefs" version of the library? I'm kind of thinking that the flow version of the library might be the one that better fits current android development patterns and hence I'm contemplating not releasing the prefs version of the library at all.

**Comment by dmitry-ryadnenko-izettle** [comment]
Thank you for the answer Erik! I think we would need the prefs one, we have a synchronous middle layer right now, you know :)

**Comment by erikeelde** [comment]
Thanks for the feedback. I'll make a prefs library release as well then. :)

**Comment by erikeelde** [comment]
Give it a squeeze and don't hesitate to provide feedback:

```
repositories {
    maven("https://s01.oss.sonatype.org/content/repositories/snapshots")
}
```

```
dependencies {
    implementation("se.eelde.toggles:toggles-flow:0.0.1-SNAPSHOT")
    implementation("se.eelde.toggles:toggles-prefs:0.0.1-SNAPSHOT")
}
```

**Comment by dmitry-ryadnenko-izettle** [comment]
Thank you Erik a lot! We'll check this out ❤️

**Comment by erikeelde** [comment]
I'm giving the libs a few spins myself and will push to central if nothing arises.

**Comment by erikeelde** [comment]
@dmitry-ryadnenko-izettle Think I've done my testing now. :) How are you guys getting along?

**Comment by dmitry-ryadnenko-izettle** [comment]
Hi Erik, we have this pretty high on our list of our priorities, but there were even more pressing issues on us right now. I expect that we'll start on this pretty soon, in 2-4 weeks, but I'm not 100% sure.

**Comment by erikeelde** [comment]
@dmitry-ryadnenko-izettle I'll push current version to maven soon then and feel free to feedback if/when you get around to. :) It should ease testing if nothing else.

**Comment by dmitry-ryadnenko-izettle** [comment]
That sounds great, thank you Erik 🙏

**Comment by erikeelde** [comment]
https://search.maven.org/search?q=se.eelde.toggles
