### ISSUE TITLE
Can't install both Wrench and Toggles on the same device

### ISSUE THREAD

**Issue by dmitry-ryadnenko-izettle** [erikeelde/toggles#39]
Looks like both app declare the same permission and Android doesn't allow to install two apps that declare the same permission on the same device. It's not a big deal, but would be convenient to be able to have both on the same device since we'll be able to test olden commits without the need to reinstall the apps. But this is a very minor issue I would say. Posting it here mostly for the record, so it's known it exists.

**Comment by erikeeldetopgolf** [comment]
@dmitry-ryadnenko-izettle Toggles declares the same provider and Wrench did - so should work with all apps - historical and future. :)

**Comment by erikeelde** [comment]
Toggles declares the wrench provider aswell. So it should just work if you uninstall wrench. Including historic commits

**Comment by dmitry-ryadnenko-izettle** [comment]
Thank you Erik, we will if something will pop up :)
