### ISSUE TITLE
gradle sync failed

### ISSUE THREAD

**Issue by tingnapianhai** [erikeelde/toggles#9]
Gradle sync failed, @erikeelde any tips or suggestions on how to solve it ?

<img width="960" alt="sync_failed" src="https://user-images.githubusercontent.com/1044872/96791615-565cbe80-142b-11eb-824d-cd4c46042953.png">

**Comment by erikeelde** [comment]
Did you check the logs? :) 
It's the [optimisations checker](https://github.com/erikeelde/gradle-optimization) that is upset about something - can you see what it's complaining about specifically? 
If it's an optimisation - would you want to enable it / be able to avoid enabling it?
I've been considering pushing an update for it regardless (found some minor issues that I'd wanna get fixed).

**Comment by tingnapianhai** [comment]
this is solved by the solution provided by @erikeelde 👍 
-> running `./gradlew checkBuildOptimizations` to check more details of error. 

(my case is to add the `xms` value in global gradle)

**Comment by tingnapianhai** [comment]
Issue solved, close the issue.
